---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-website-app
  # namespace: ns-simple-flask-website-app
spec:
  selector:
    matchLabels:
      app: simple-flask-website-app
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-flask-website-app
    spec:
      containers:
        - name: simple_flask_app
          image: registry.ram-iyer.com/simple_flask_app
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred

