---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-website-app
spec:
  selector:
    matchLabels:
      app: simple-flask-website-app
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-flask-website-app
    spec:
      containers:
        - name: simple-flask-website
          image: registry.ram-iyer.com/simple-flask-website
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred

